### PR TITLE
#72: Added list of AmsterdamPHP videos

### PR DESCRIPTION
**Pull request by pascaldevink**
# What
Implementation of #72, building on #77. Added a list of AmsterdamPHP videos from YouTube, replacing the list of blog posts.

# How it looks
screen shot 2015-04-18 at 21 05 52

### CODE REVIEW

**Comment by WyriHaximus** [comment]
:+1: :+1: This looks pretty neat. Although the video sorting seems off...

**Comment by pascaldevink** [comment]
That's actually how it was uploaded. The October talk came in late 😕

**Comment by WyriHaximus** [comment]
Ah that explains! :+1:

**Comment by rdohms** [comment]
What data does youtube provide? Can we try to separate date/title? Regexp should solve the title, but can we extract the date directly?

**Comment by WyriHaximus** [comment]
[This method on the API is called](https://developers.google.com/youtube/v3/docs/playlistItems/list) and it returns a list of [playlistItems](https://developers.google.com/youtube/v3/docs/playlistItems#resource).

**Comment by pascaldevink** [comment]
YouTube provides a separate date, but the date that we currently display is in the title. We can separate those, but that means that the title should stay in this particular format.

**Comment by pascaldevink** [comment]
One option would be to drop everything in the title up to the colon (:) and put in the date YouTube provides. The thing is that publication date doesn't say much. The currently displayed date is the date of the recording. I'm guessing that's more important to people than the publication date.

**Comment by rdohms** [comment]
Yeah ideally we should reg-exp the date out of the title and use just the month... but it is "fragile" to some extent

**Pull request merged**
